### ISSUE TITLE
Running fQTL on summary statistics

### ISSUE THREAD

**Issue by phuwanat** [YPARK/fqtl#2]
Hello,

I read your BioRxiv paper and found it very interesting. I'm going to use fQTL with my summary statistics data. Do you have some suggestions on doing this?

**Comment by YPARK** [comment]
You should first have individual-level reference eQTL data : gene expression and genotypes.  Once you trained the model, I suggest Sasha Gusev's summary-based TWAS method.

**Comment by phuwanat** [comment]
Thank you. Do you have a plan to release GTEx's trained weights from TWAS using fQTL ?

**Comment by YPARK** [comment]
Hi, We are working on that.  We are looking to find best way to share weights.  Currently it would be just gzipped text files.  Do you have better suggestions?

**Comment by phuwanat** [comment]
That would be great.

I think releasing gzipped files of each gene for each tissue and their corresponding .pos and other could be fine. It will be the same way that Gusev et al. made their trained weights available. So that, the community can try their summary statistics on orginal expression weights and fQTL weights.

Thanks
